In [1]:
import pandas as pd

In [8]:
#Read the csv file to a pandas df
df = pd.read_csv("Data/survey_result_clean_renamed.csv")

In [9]:
#Look at the head of the data
df.head()

,Unnamed: 0,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,...,InteractOutsideOfImmediateTeam,KnowledgeSilo,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,SupportNewHiresOnboarding,LearnResourcesProvidedByEmp,GiveTimeToLearnNewSkill,ConvertedCompYearly
0,0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40205.0
3,3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215232.0
4,4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.columns

Index(['Unnamed: 0', 'ResponseId', 'MainBranch', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency',
       'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use',
       'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith',
       'Blockchain', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'Age', 'Gender', 'Sexuality', 'Ethnicity', 'Accessibility',
       'TBranch', 'ICorPM', 'WorkExp', 'InteractOutsideTeam',
       'KnowledgeSiloPrevent', 'UpToDateOrgInfo', 'FindAnsW/Tools',
       'KnowHowToFindAns', 'AnsQWhichAlreadyAnsBefore', 'WaitForAnsRuinW/Flow',
       'NeedHelpOutsideOfImmediateTeam', 'InteractOutsideOfImmediateTeam',
       'KnowledgeSilo', 'TimeSearching', 'TimeAnswering', 'Onboarding',
       'ProfessionalTech', 'SupportNewHiresOnboarding',
       'LearnResourcesProvidedByEmp', 'GiveTimeToLearnNewSkill',
       'ConvertedCompYearly'],
      dtype='object')

In [5]:
df["LanguageHaveWorkedWith"].head()

0                                            NaN
1                          JavaScript;TypeScript
2              C#;C++;HTML/CSS;JavaScript;Python
3                   C#;JavaScript;SQL;TypeScript
4    C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript
Name: LanguageHaveWorkedWith, dtype: object

In [6]:
df["LanguageHaveWorkedWith"].value_counts()

LanguageHaveWorkedWith
HTML/CSS;JavaScript;TypeScript                                                              1250
Python                                                                                       962
HTML/CSS;JavaScript                                                                          914
HTML/CSS;JavaScript;PHP;SQL                                                                  745
C#;HTML/CSS;JavaScript;SQL;TypeScript                                                        570
                                                                                            ...
C#;Java;JavaScript;PHP;PowerShell;SQL;TypeScript                                               1
C++;HTML/CSS;JavaScript;Python;Solidity;SQL                                                    1
Dart;Haskell;HTML/CSS;Java;R;SQL;TypeScript                                                    1
Bash/Shell;C;C#;Go;HTML/CSS;Java;JavaScript;Lua;Perl;PHP;Python;Ruby;Rust;SQL;TypeScript       1
C#;JavaScript;Lua;PowerShell;SQL;TypeScript                                                    1
Name: count, Length: 25068, dtype: int64

In [12]:
df["DatabaseHaveWorkedWith"].value_counts()

DatabaseHaveWorkedWith
MySQL                                                                3563
PostgreSQL                                                           3519
Microsoft SQL Server                                                 3238
SQLite                                                               2022
MongoDB                                                              1655
                                                                     ...
Elasticsearch;IBM DB2;MongoDB;MySQL                                     1
Cloud Firestore;Microsoft SQL Server;MongoDB;MySQL;Neo4j                1
Cloud Firestore;MongoDB;Oracle;PostgreSQL;Redis;SQLite                  1
MariaDB;Microsoft SQL Server;MySQL;Neo4j;Oracle;PostgreSQL;SQLite       1
Microsoft SQL Server;Neo4j;Redis                                        1
Name: count, Length: 4223, dtype: int64